name: cs168-project
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - cpuonly
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - tqdm
  - scikit-learn
  - gym
  - autopep8
